### ISSUE TITLE
ACTIVIDAD 8 ENTREVISTA

### ISSUE THREAD

**Issue by YaelTrinidad** [SistemasTecTlaxiaco/actividad-8-entrevista-equipo-2#1]
[Entrevista Equipo DINAMITA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-entrevista-equipo-2/files/9880525/Entrevista.Equipo.DINAMITA.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica has obtenido el 20% del 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
